version: "3.8"

services:
  nginx:
    build:
      target: dev
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"

  php:
    build:
      target: dev
      args:
        GIT_USER: ${GIT_USER}
        GIT_USER_MAIL: ${GIT_USER_MAIL}
    stdin_open: true
    tty: true
    ports:
      - "2323:22"
      - "9003:9003"
    volumes:
      - ./.docker/scripts/laravel_init:/opt/files/laravel_init
      - vs-server:/${APP_USER}/.vscode-server

  pgsql:
    ports:
      - "${POSTGRES_HOST_PORT}:5432"

  redis:
    ports:
      - "6379:6379"

volumes:
  vs-server:
    driver: local
