version: "3.8"

services:
  nginx:
    build:
      target: dev
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"

  php:
    build:
      target: dev
    ports:
      - "2323:22"
      - "9003:9003"
    volumes:
      - ./.docker/scripts/laravel_init:/opt/files/laravel_init
      - vs-server:/${APP_USER}/.vscode-server

  pgsql:
    ports:
      - "5432:5432"

  redis:
    ports:
      - "6379:6379"

  phppgadmin:
    container_name: phppgadmin
    image: bitnami/phppgadmin:7
    environment:
      DATABASE_HOST: ${PHP_PG_ADMIN_DATABASE_HOST}
      DATABASE_PORT_NUMBER: ${PHP_PG_ADMIN_DATABASE_PORT_NUMBER}
    ports:
      - "81:8080"
      - "444:8444"
    depends_on:
      - pgsql

volumes:
  vs-server:
    driver: local
