#!/bin/bash

# Install Composer dependencies
composer install -d "${APP_CODE_PATH_CONTAINER}/project"

# Deal with the .env file if necessary
if [ ! -f "${APP_CODE_PATH_CONTAINER}/project/.env" ]; then
    # Create .env file
    cp "${APP_CODE_PATH_CONTAINER}/project/.env.example" "${APP_CODE_PATH_CONTAINER}/project/.env"

    # Generate application key
    php "${APP_CODE_PATH_CONTAINER}/project/artisan" key:generate --ansi
fi

# Yarn install
yarn --cwd "${APP_CODE_PATH_CONTAINER}/project" install

# Database
php "${APP_CODE_PATH_CONTAINER}/project/artisan" migrate
