#!/bin/bash

# Install Composer dependencies
composer install -d "/var/www/html"

# Deal with the .env file if necessary
if [ ! -f "/var/www/html/.env" ]; then
    # Create .env file
    cp "/var/www/html/.env.example" "/var/www/html/.env"

    # Generate application key
    php "/var/www/html/artisan" key:generate --ansi
fi

# Yarn install
yarn --cwd "/var/www/html/" install

# Database
php "/var/www/html/artisan" migrate
